[perspective]
	#The default perspective when you load the game.
	#Allowed Values: FIRST_PERSON, THIRD_PERSON_BACK, THIRD_PERSON_FRONT, SHOULDER_SURFING
	default_perspective = "SHOULDER_SURFING"
	#Whether or not to replace the default third person perspective.
	replace_default_perspective = true