#Server Settings
[server]
	[server.nerfs]
		#Determines if too many backpacks in player's inventory cause slowness to the player
		tooManyBackpacksSlowness = true
		#Maximum number of backpacks in player's inventory that will not cause slowness
		# Default: 3
		# Range: 1 ~ 27
		maxNumberOfBackpacks = 3
		#Ratio of slowness levels per every backpack above the maximum number allowed. (number of backpacks above the max gets multiplied by this number and ceiled)
		# Default: 1.0
		# Range: 0.1 ~ 5.0
		slownessLevelsPerAdditionalBackpack = 3