name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "1.3.0 Beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a9d04fe7518a0c02849ee65587f78a2997fe2b68346c69a90e6b0a38ae9f3c9"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
