name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8691ebdcf25318476a6f948d88d883ed3b907482c5ac73b77419abf88f707ba"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
