name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "1.3.0 Beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dd50b5a1a6b9a5f8d39743e98208f3bf0f24340229fcd492b802a75075d6177"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
