name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "1.3.0 Beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a92644c112617355830942e368d9454b685045e301c9d0a4645db2bf417ba6a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
