name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "2.0.0 Beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a994f53687cdc9bd11f1d6df0f384982416837bb2efa83a13b41c571cab2e7b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
