name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "1.3.0 Beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "180acf3a80e8cc00c545096a5aa95cb2a05530c1d1268cc4c4cfb6378b251ace"

[versions]
fabric = "0.18.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
