name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "1.0 Beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f91ac692f9a96d874919fd74e88584d2ffa9023981d29a8c908fa767601f967b"

[versions]
fabric = "0.18.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
