name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b5853c348dd8b2c16c9ff232ac095f564fef95bc122e05f800055d1094e9ebd"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
