name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "1.0.2 Beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a1ccfff5e3e14699910a2e25902864c61404a28d9cda28a561aa7df3e79f50c"

[versions]
fabric = "0.18.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
