name = "JeCobblemon"
author = "WxAaRoNxW, JecoLambo"
version = "1.0.1 Beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8096708f8358f32ed56e8e4c66cd8b0071315330eb71bc5a004d98d1a2e63f5"

[versions]
fabric = "0.18.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
datapack-folder = "./global_packs/required_data"
